[[snippets]]
  description = "I have an apple"
  command = "comm"

[[snippets]]
  description = "hoge"
  command = "cat"

[[snippets]]
  description = "teset"
  command = "hoge fuga 1 2 | aba"

[[snippets]]
  description = "show files"
  command = "ls -la"

[[snippets]]
  description = "count the number of files"
  command = "ls | wc -l"

[[snippets]]
  description = ""
  command = "echo"

[[snippets]]
  description = "Confirm expiration date of ssl certificate"
  command = "echo | openssl s_client -connect example.com:443 2>/dev/null |openssl x509 -dates -noout"

[[snippets]]
  description = "SS有効期限を確認する"
  command = "echo | openssl s_client -connect example.com:443 2>/dev/null |openssl x509 -dates -noout"

[[snippets]]
  description = "ls"
  command = "ls"

[[snippets]]
  description = "ls2"
  command = "ls"
